import "./globals.css";
import { ReduxProvider } from "@/Components/ReduxProvider";
import LayoutWrapper from "@/Components/LayoutWrapper"; // <- move logic here

export const metadata = {
  title: "Marshee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-black text-white">
        <ReduxProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
